### ISSUE TITLE
Conflict with lualine

### ISSUE THREAD

**Issue by f3fora** [andersevenrud/nordic.nvim#2]
[lualine](https://github.com/hoob3rt/lualine.nvim) with nord theme do not start with this plugin raising this error:

```
lualine.nvim/lua/lualine/highlight.lua:22: Vim(highlight):E411: highlight group not found: lualine_a_normal_to_lualine_c_normal
```

**Comment by maaslalani** [comment]
Thanks for creating this issue! I will have a look and try to fix this :)

**Comment by maaslalani** [comment]
I was able to get `lualine` working and not able to reproduce your issue. Can you share your configuration with me?

![image](https://user-images.githubusercontent.com/42545625/112871701-84ef5d00-908d-11eb-85a6-27e5c89c06fe.png)

**Comment by f3fora** [comment]
I found the issue and how to solve it.
You need to initialize lualine after running `.use{}`, because `vim.cmd("hi! clear")` at line 43 deletes all color settings, lualine can't find them and so it crash.
I suggest to remove that command.
