### ISSUE TITLE
Improve `startuptime` for nordbuddy

### ISSUE THREAD

**Issue by maaslalani** [andersevenrud/nordic.nvim#24]
Startup time for `nordbuddy` is quite bad. It takes about `26ms` + `36ms` to get it up and running.

```
062.231  026.703  026.703: sourcing /nix/store/f5lbys30l87chdwjm72w9wfd8wslhvsh-vim-pack-dir/pack/home-manager/start/nordbuddy/colors/nordbuddy.lua
114.187  036.558  036.558: sourcing /nix/store/f5lbys30l87chdwjm72w9wfd8wslhvsh-vim-pack-dir/pack/home-manager/start/nordbuddy/colors/nordbuddy.lua
```

I tested with [`nord.nvim`](https://github.com/shaunsingh/nord.nvim) and [`nord.vim`](https://github.com/arcticicestudio/nord-vim) and those are definitely faster (I do still like our colours and how they look better, though so I don't want to switch to those plugins).

Maybe we can remove the dependency on `colorbuddy`?

**Comment by andersevenrud** [comment]
Is it possible to get a deeper trace to see hotspots in the code?

**Comment by andersevenrud** [comment]
Apparently this is the hot spot: https://github.com/maaslalani/nordbuddy/blob/611dbfd69ae9a682cd3c4ff174c24837cc680e69/lua/nordbuddy/init.lua#L73

Doesn't seem like too much of a job to cut out `colorbuddy` here though. I'll play around with this.

**Comment by maaslalani** [comment]
Ahh interesting thanks for looking into this, how were you able to trace the hotspots?

**Comment by andersevenrud** [comment]
I started reading up on profiling, but I had a hunch in the back of my mind, so instead i just started removing the colorbuddy calls from bottom up. I got a lucky as the first one was this grouping call, and it went from ~20ms to basically zero.

**Comment by maaslalani** [comment]
I guess that does makes sense if you remove that line since its being called a bunch of times for all the color groups. It is a colorbuddy function though, so I do wonder if something is going on there as well. It might speed things up a bit if we just have a very simple plugin that didn't use colorbuddy.

**Comment by andersevenrud** [comment]
I've looked at the group codebase, and there's certainly a lot going on there that has some overhead, like parameter validation and color calculations (ex. HSL values).

Also, seeing that we're using the palette as-is and not adjusting it with lighthen/darken, etc. there's not much point in relying on colorboddy.

So just applying these hightlights and the basic vim options to make it detect -- I'm all for!

**Comment by maaslalani** [comment]
Yea I agree! In an earlier version I did a lot of stuff with lighten and darken but we don't anymore

**Comment by andersevenrud** [comment]
It was actually used here: https://github.com/maaslalani/nordbuddy/blob/main/lua/nordbuddy/colors/neogit.lua (and some other places)

Though, if something like this is needed I can write a quick and dirty function for that. Going to leave it static for now in my refactor testing here.

**Comment by maaslalani** [comment]
@andersevenrud 
I made a quick PR https://github.com/maaslalani/nordbuddy/pull/26

**Comment by maaslalani** [comment]
This is what the colorscheme would look like https://github.com/maaslalani/nordbuddy/blob/cd60ab43242f775f97ebaa77d763cb2463fd5f96/lua/nordbuddy/init.lua

**Comment by maaslalani** [comment]
Going to test the startup time now

**Comment by andersevenrud** [comment]
After my current changes :nerd_face: 

```
035.048  001.943  001.943: sourcing /home/anders/.local/share/nvim/site/pack/packer/start/nordbuddy/colors/nordbuddy.lua
```

**Comment by maaslalani** [comment]
No way! Thats fantastic!

**Comment by maaslalani** [comment]
Feel free to make a PR and we can merge yours!

**Comment by andersevenrud** [comment]
PR comes as soon as I have tidied up a bit :D
