### ISSUE TITLE
Lualine Theme

### ISSUE THREAD

**Issue by f3fora** [andersevenrud/nordic.nvim#28]
Even if [lualine](https://github.com/hoob3rt/lualine.nvim) includes a [Nord Theme](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/themes/nord.lua), should we add one for consistency? 

Other colorschemes already do this. For example [nord.nvim](https://github.com/shaunsingh/nord.nvim/blob/master/lua/lualine/themes/nord.lua).

**Comment by maaslalani** [comment]
Is there any reason to? I like lualine's nord theme, so it seems unnecessary to add one unless you want to change the colours?

**Comment by f3fora** [comment]
Having the same maintainers for all the colorscheme instead of relying on different people.

**Comment by andersevenrud** [comment]
I don't see much reason to so if everyone is fine with the lualine color definitions.

**Comment by maaslalani** [comment]
I agree with @andersevenrud, not much reason to duplicate and override code. We can always submit PRs to lualine as well.

FWIW I liked the default lualine nord colours a lot more than the nord.nvim ones.

**Comment by andersevenrud** [comment]
I also think the lualine one is sufficient (and preferable).

So I guess we can close this one ?! That's what I'm doing anyways. Just re-open if you wanna keep the discussion rolling :)
