### ISSUE TITLE
Single file definitions

### ISSUE THREAD

**Issue by maaslalani** [andersevenrud/nordic.nvim#29]
What do you all (@andersevenrud @f3fora) think about not having all the colors defined in a bunch of different files, it makes it really hard for me to quickly test out new colors because I use nix/home-manager so I can't just `:luafile %` like I used to do so it makes it difficult, also I'm not convinced creating a new file for each plugin is the best organization. It's nice, but I think having everything in one file makes searching super easy and makes everything easily understandable if its all just one file.

**Comment by maaslalani** [comment]
Mainly though it's just an issue of running `:luafile %` so that I can see color changes very quickly, so if either of you know an alternative that lets me source the plugin without running `home-manger switch` then I would love to know (and happy to keep it like the way it is). How do you all source/view changes?

**Comment by andersevenrud** [comment]
plenary has a handy function you can use to clear require cache:

```
:lua require'plenary.reload'.reload_module('nordbuddy') -- This is a match, so all sub modules are included
:colorscheme nordbuddy
```

**Comment by andersevenrud** [comment]
one-liner: `:lua require'plenary.reload'.reload_module('nordbuddy'); vim.cmd'colorscheme nordbuddy'`

**Comment by maaslalani** [comment]
Oh sweet, I'll try this out! Thanks a bunch

**Comment by andersevenrud** [comment]
> everything in one file makes searching super easy and makes everything easily understandable if its all just one file.

I guess this depends on the method of search and what kind of workflow you use. Using a fuzzy searcher makes getting around pretty trivial, but I totally get what you mean here: I like the convenience of having things in one place (as you can see in my [neovim config](https://github.com/andersevenrud/dotfiles/tree/master/.config/nvim) :sweat_smile: ).

However, I think there's some value in having it organized like it is right now. No strong feelings though :)

**Comment by maaslalani** [comment]
👍  I think I'm fine with this organization as long as I figure out how to hot-reload my stuff, definitely a "me" problem 😄  So far no luck on the `plenary` stuff because of how I load my plugins, but I think I'm on the right track

**Comment by andersevenrud** [comment]
Ah. I just looked at your setup an you're using Fennel. I gotta show this and neovim's Lua to some of the Lispers (so, Emacs) at work that dabble in vim. They're gonna love that :D

**Comment by maaslalani** [comment]
Yea haha I switched to it recently after watching https://www.youtube.com/watch?v=VC1DhAoRSpg

It's a pretty good time + theres https://fennel-lang.org/see so it's super easy to just copy & paste lua code and get the equivalent lisp out and then hand optimize it from there.

**Comment by andersevenrud** [comment]
It looks cool, but being mostly a web tech developer, it's kind of a breath of fresh air to work with something as simple as Lua. No transpilers or a bunch of tools in the stack. There are some quality of life stuff that I sorely miss from other languages (Lua 5.1 doesn't even have bitwise operators)...but it does the job just fine :sweat_smile:

**Comment by andersevenrud** [comment]
I would probably use something other than Lua for projects I was making for public use though. Teal was the first one I came across while contributing to some neovim related stuff. But Fennel is now on my list as well. Sorry... this got a bit off-topic :D

**Comment by maaslalani** [comment]
Haha yea I don't think you're missing out by not using it. Yea Teal looks super cool.
Okay I think I got it working at least to where my plugin references a local copy of nordbuddy so we can close this for now!

**Comment by maaslalani** [comment]
Do let me know the cool stuff you come across! I love discovering and learning new technologies. I would be down to use Teal with nordbuddy if you want 😄  (might be overkill for a color plugin though 😂 )
