### ISSUE TITLE
[Feature Request]: Option to toggle statusline minimal

### ISSUE THREAD

**Issue by sandersantema** [andersevenrud/nordic.nvim#31]
Although I understand why a more minimal look such as introduced in b97e5c792138a7d5976ee7de70f9a85015043101 would be desirable for me personally it's not a good fit. Might I suggest introducing a toggle for this kind of highlighting?

If I were to take a more utilitarian standpoint I'd even suggest reverting this chance regardless of the aesthetic desirability. With this new minimal statusline colorscheme there is no clear delineation between windows. Apart off any text you might have in your statusline which differs per setup and can therefore not be relied upon. However small the influence of this change might be, I do think this makes nvim less useful. 

Nvim being less useful trumps the aesthetic desirability of a colorscheme since the purpose of nvim itself is to be useful, that of a colorscheme to be useful in the first place and beautiful second. If nvim is less useful the aesthetic desirability of a colorscheme has less value. 

A toggle would be a good solution but I'd rather not see the usability of the colorscheme decrease by making it more and more minimal in general.

But then again, it's quite a harmless change and easy for me to revert for my personal install so no harm done :)

**Comment by andersevenrud** [comment]
> there is no clear delineation between windows

Yeah, I agree here. The statusline needs a little bit of contrast.

**Comment by maaslalani** [comment]
Hey! Thanks for using nordbuddy! I'll revert the minimal changes and add a toggle for "minimal" styles. Thanks so much for the feedback

**Comment by sandersantema** [comment]
I think this issue can be closed, thank you for the quick resolution and creating nordbuddy in the first place! Although I'll leave it open for now in case you want to track implementing the toggle for the minimal style.
