### ISSUE TITLE
Diff added items not highlighted in packer.nvim

### ISSUE THREAD

**Issue by wimstefan** [andersevenrud/nordic.nvim#39]
packer.nvim offers the possibility to show a diff summary of updated plugins. Lines which are added are not highlight in this summary since packer.nvim uses the `DiffAdded` highlight which is not mapped in `nordbuddy`.

This little patch adds the missing highlight.

```diff
diff --git a/lua/nordbuddy/colors/diff.lua b/lua/nordbuddy/colors/diff.lua
index 4487702..cc2bc05 100644
--- a/lua/nordbuddy/colors/diff.lua
+++ b/lua/nordbuddy/colors/diff.lua
@@ -1,6 +1,7 @@
 return function(c)
     return {
         {'DiffAdd', c.green, c.black},
+        {'DiffAdded', c.green, c.black},
         {'DiffChange', c.yellow, c.black},
         {'DiffDelete', c.red, c.black},
         {'DiffText', c.red, c.black}
```

**Comment by andersevenrud** [comment]
Thanks for raising this issue. It will be taken care of ASAP :)

**Comment by wimstefan** [comment]
Wow you guys are fast! :D

And I also want to compliment you with the design of this wonderful colourscheme :clap: :clap: :clap:
Even a intellectually limited person as I am can read and understand that code. I might as well use it as a template to migrate my own colourscheme to Neovim if that's OK with you guys ...

**Comment by andersevenrud** [comment]
Glad you like it! :)

Feel free to use it in your own projects. Just make sure to read the license first.
