### ISSUE TITLE
Certain highlights broken when using impatient.nvim

### ISSUE THREAD

**Issue by sandersantema** [andersevenrud/nordic.nvim#41]
How it looks without a colorscheme (don't mind the awful contrast of the default colorscheme and my terminal background):
![image](https://user-images.githubusercontent.com/21057514/132238413-367dee83-62a6-415c-887c-791fccf73a4a.png)

How it looks with nordbuddy:
![image](https://user-images.githubusercontent.com/21057514/132238614-8ad2101e-b19c-4f14-b94a-94723688de80.png)

This is my nordbuddy setup (as seen in the screenshots):
```lua
require("nordbuddy").colorscheme({
  italic = false,
  italic_comments = false,
})
```

This is using the latest nordbuddy 525b9658fcf145e141f34de16029bb069ced92fd and the latest neovim 
3f526feebfe6d7bf71380a24639a3dd908f77ff6 (although I've had this problem for a bit longer). This might not be enough information to debug but I wouldn't know what to add exactly so if you miss anything please ask.

**Comment by andersevenrud** [comment]
Strange. I'm not able to reproduce this :thinking: I'll do a bit more testing here on my end.

**Comment by andersevenrud** [comment]
Could you maybe share what terminal you're using as well as your `$TERM` variable ?

**Comment by maaslalani** [comment]
Not able to reproduce either, I see this when visually selecting:

![image](https://user-images.githubusercontent.com/42545625/132248345-95408b67-fe83-48a4-b45d-63fd6624e360.png)

**Comment by andersevenrud** [comment]
Tried a couple of different terminal emulators as well as a couple of variations of `$TERM` (including inside tmux), and so far I haven't run into this.

**Comment by andersevenrud** [comment]
It also dawned on me that in @sandersantema's screenshot, the active line has no highlight (not even in the gutter -- text should be "white" there). This should have the same background as "visual mode".

**Comment by sandersantema** [comment]
I'm using `konsole 21.08.0` but I've tested it with `xterm 368-2.1` too and this gives the same result. Whether I'm using `tmux` or not doesn't matter either, in `tmux` `$TERM` is set to `tmux-256color` without `tmux` `$TERM` is set to `xterm-256color`. I'll try to setup a minimal config and see if I'm still experiencing this error.

**Comment by sandersantema** [comment]
Hmmphh for some reason I'm not able to get the minimal config working, do any of you have an idea how to get it working?
```vimscript
let &runtimepath  = '/home/sandersantema/.local/share/nvim/site/pack/packer/start/nordbuddy,' . &runtimepath
let g:nord_underline_option = 'none'
let g:nord_italic = v:true
let g:nord_italic_comments = v:false
let g:nord_minimal_mode = v:false
colorscheme nordbuddy
```

**Comment by andersevenrud** [comment]
I was able to run with a minimal config using `-u customvimrc` -- though, I had to temporarily rename my `~/.config/nvim` directory because it always tried to load (probably related to the runtimepath concatenation -- I've never messed with that before).

```vim
let &runtimepath  = '/home/anders/.local/share/nvim/site/pack/packer/start/nordbuddy,' . &runtimepath
set termguicolors
colorscheme nordbuddy
```

**Comment by sandersantema** [comment]
Moving `~/.config/nvim` did the trick and highlighting works using this minimal config. So I guess this is caused by my config or another plugin, that I'll have to investigate further. I'll get back to you when I have this figured out but it could take a little longer.

**Comment by andersevenrud** [comment]
Alright. Great! I'll just leave this open then until you've narrowed it down.

**Comment by sandersantema** [comment]
Found it :tada: I stumbled upon it by accident and I've got no idea why it's the case but it seems to have something to do with [impatient.nvim](https://github.com/lewis6991/impatient.nvim). Highlighting works once after clearing it's cache (`:LuaCacheClear`) and restarting neovim afterwards it doesn't. Disabling impatient.nvim all together gets the highlighting working again. 

impatient.nvim provides quite a big improvement to startup time but I have no idea whether highlighting isn't working with nordbuddy and impatient.nvim because of my setup, nordbuddy or impatient.nvim. If you'd like to investigate feel free to otherwise it might be a good idea to at least post a warning impatient.nvim could cause some problems with highlighting. Whenever I get around to it I'll try to reproduce with a minimal config and see if it's my config causing the problems.

**Comment by andersevenrud** [comment]
Ah. Nice find!

I've seen this impatient thing pop up every now and then while I'm browsing, but never tried using it because my load time is 200ms, which is basically a blink of an eye and totally fine :sweat_smile: 

I'll install it and do a bit of debugging to get (hopefully) a better idea of what's going on.

*Edit*: Instant result. Highlight is missing. Investegating...

*Edit*: Changed issue title.

**Comment by andersevenrud** [comment]
OK. So I've figured what's causing the issue, but not exactly sure why.

---

https://github.com/maaslalani/nordbuddy/blob/becd30e3c82a9c2a437c30f5f9e249becabfd30d/lua/nordbuddy/init.lua#L67-L72

The `unpack` here results in `nil` values when a module is brought back from the impatient cache.

The `group` always has the table: `{ "Visual",  [3] = "#434c5e" }`, but unpack yields `nil`.

Example before: `Visual nil #434c5e nil`, and after: `Visual nil nil nil`.

---

Doing this works:

```lua
vim.highlight.create(group[1], {
    guifg = group[2] or 'NONE',
    guibg = group[3] or 'NONE',
    gui = group[4] or 'NONE',
})
```

The following `unpack` above seems to work fine though.

https://github.com/maaslalani/nordbuddy/blob/becd30e3c82a9c2a437c30f5f9e249becabfd30d/lua/nordbuddy/init.lua#L55

**Comment by andersevenrud** [comment]
I pushed the changes I mentioned here. Hopefully that takes care of it :nerd_face: 

I would love to know exactly why this does not work though instead of this somewhat "blind" fix..  Oh well. I might just open an issue or something about it [in impatient] if I can make a minimum reproducible example.

**Comment by maaslalani** [comment]
Thanks @andersevenrud for looking into this ❤️❤️
