### ISSUE TITLE
Support for nvim-cmp's kind completion highlights

### ISSUE THREAD

**Issue by gegoune** [andersevenrud/nordic.nvim#45]
FYI, in case you want to support it: cmp recently added support for changing colours for different completion kinds: https://github.com/hrsh7th/nvim-cmp/commit/593a6345de3b8186a3b5d5501b6e137ca17f1653. Apologies for not creating PR but my styling skills are non existant.

**Comment by andersevenrud** [comment]
This has already been added :)

https://github.com/andersevenrud/nordic.nvim/pull/44

**Comment by gegoune** [comment]
Ah, I see, sorry about the noise then. I did have latest version installed but did not see it during tests as not all kinds are styled.

**Comment by andersevenrud** [comment]
If you have suggestions for the rest of the kinds feel free to place them here and I'll have a look.

**Comment by gegoune** [comment]
Will see if I can come up with anything that doesn't look super ugly.
