### ISSUE TITLE
Alternative background for special buffers and certain extensions

### ISSUE THREAD

**Issue by gegoune** [andersevenrud/nordic.nvim#46]
Mainly background style for buffers such nvim-tree, vista, undo-tree  or quickfix (etc). Seems to be popular recently and I quite liked it in other colorschemes. What do you think?

**Comment by andersevenrud** [comment]
Could be added as an option maybe ? What do you think about this @maaslalani ?

**Comment by maaslalani** [comment]
I don't use any of those plugins/buffers (other than quickfix) so doesn't affect me, i think having a different background makes sense as long its not too drastic. If users complain, then could add an option like the minimal mode stuff. But yea up to you entirely, as long as it looks good 😄

**Comment by gegoune** [comment]
Absolutely could be an option. Would be nice if there was an option to specify what should be styled as well.

Example: https://github.com/folke/tokyonight.nvim/search?q=sidebars

**Comment by andersevenrud** [comment]
> Would be nice if there was an option to specify what should be styled as well.

Indeed. Noted!

>  as long its not too drastic

Yeah... We'll definitively need a new color in the palette for this because the contrast will be rather extreme with the current choices imo (or maybe it's just because I'm totally not used to having different buffer backgrounds).

---

I'll look into this and get back to you @gegoune .

**Comment by andersevenrud** [comment]
Here are two variants based on the background color, but stepped down 1 and 2 steps respectively :thinking: 

---

![2021-11-29-195927_3840x2160_scrot](https://user-images.githubusercontent.com/161548/143927037-3ef4457a-74c8-4416-b9a8-554f1145d7d2.png)
![2021-11-29-195931_3840x2160_scrot](https://user-images.githubusercontent.com/161548/143927040-8bef0017-6257-44be-9c2b-36f0fa0a415a.png)

---

![2021-11-29-200213_3840x2160_scrot](https://user-images.githubusercontent.com/161548/143927302-7a2be74a-fa6c-4272-a70d-e9ca74d29421.png)
![2021-11-29-200217_3840x2160_scrot](https://user-images.githubusercontent.com/161548/143927308-86992c72-756d-4d66-a5d2-0ba4d83bef8f.png)

**Comment by andersevenrud** [comment]
Any preference ? Personally, I'm leaning towards the first variant because it's quite subtle.

**Comment by maaslalani** [comment]
I'm a fan of the first variant! Second one is a little too contrasting with the background.

**Comment by gegoune** [comment]
Either one works for me to be honest. Thank you very much for super quick implementation!

**Comment by andersevenrud** [comment]
I've opened a PR of this here: https://github.com/andersevenrud/nordic.nvim/pull/47

Just gotta figure out a nice way to add autocomands for special buffers because highlight groups doesn't cover things like the quickfix and terminals :thinking:

**Comment by maaslalani** [comment]
> I've opened a PR of this here: #47
> 
> Just gotta figure out a nice way to add autocomands for special buffers because highlight groups doesn't cover things like the quickfix and terminals 🤔

You _might_ need to check the filetype (`filetype=qf`)

**Comment by andersevenrud** [comment]
Yeah, it'll have to be an autocommand with the filetype set, which in turn sets the "Normal" highlight based on that. I think there's also a neovim native way to do this with `set`. I vaguely remember coming across this at some point.

**Comment by maaslalani** [comment]
Actually, maybe the [`QuickFixLine`](https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/theme.lua#L59) is what we need? and for terminal looks like [Tokyonight uses an autocommand](https://github.com/folke/tokyonight.nvim/blob/a5b3cbe750ed6a05a018ac81782bb01de512a6c9/lua/tokyonight/util.lua#L149-L151)

**Comment by andersevenrud** [comment]
`QuickFixLine` is just the currently selected line in qf. I already tried this :sweat_smile: 

But that autocommand has `setlocal` which was the thing I was vaguely remembering!

**Comment by andersevenrud** [comment]
The else-condition there also contains the recipe to cover terminal and a lot of other stuff as well. So thanks for that @maaslalani . I really wish that autocmd abstraction was a thing in the neovim Lua APIs by now, but seems like that won't land until 0.7 probably.... oh well :)

**Comment by andersevenrud** [comment]
@maaslalani That did the trick! PR was updated with these changes :smile:

**Comment by andersevenrud** [comment]
I have been running these changes all day and it all worked out, so I merged it. Keeping this open for a little bit in case there's any more places where this could be implemented.

**Comment by gegoune** [comment]
Thank you very much, was using it today too and it works well.

**Comment by andersevenrud** [comment]
> Keeping this open for a little bit in case there's any more places where this could be implemented.

Think I caught everything in the PR. If not, let me know and I'll add it in quickly @gegoune .

I've also started making docs (https://github.com/andersevenrud/nordic.nvim/pull/51) on how all of this works, and I'll make sure to include how to do this alternate stuff there as well.

**Comment by gegoune** [comment]
Thank you very much @andersevenrud, loving the scheme! (Go Magnus!)
