### ISSUE TITLE
Add/change highlight groups

### ISSUE THREAD

**Issue by gegoune** [andersevenrud/nordic.nvim#48]
What's the best way to add more groups (and maybe slightly override existing ones, for Telescope in my case) having access to colours defined in the scheme?

I was thinking, maybe some interface (from `setup()`) where one could have some callbacks receiving same arguments as functions in `lua/nordic/colors/`?

**Comment by andersevenrud** [comment]
If you only need the palette, then you can just do this:

```lua
local palette = require('nordic.palette')
vim.highlight.create('TelescopeSomething', { guifg = palette.red })
```

If you need the other stuff, then this could be exposed in the configuration options as a callback I suppose :thinking:

**Comment by gegoune** [comment]
Ah yeah, being able to use `cs.bg('telescope')` would be what I need for that very case.

**Comment by andersevenrud** [comment]
Try https://github.com/andersevenrud/nordic.nvim/pull/49 . It gives you the option to define colors just like in this codebase via the discussed callback.

**Comment by gegoune** [comment]
Works very nice and is exactly what I had in mind. So quick, thank you!

**Comment by andersevenrud** [comment]
Great! Then I'll merge it :smile:
