### ISSUE TITLE
Incorrect multiline string highlighting in Python

### ISSUE THREAD

**Issue by 9seconds** [andersevenrud/nordic.nvim#52]
Hey! Thanks for the amazing colorscheme. I do have a problem though with incorrect multiline string highlighting in Python :/ Please take a look at this asciinema: https://asciinema.org/a/S7uEVWTm7wxxM8un1p0uu64zH Just FYI: https://github.com/EdenEast/nightfox.nvim this guy does it correct.

**Comment by andersevenrud** [comment]
Hm. I'm not actually able to reproduce this.

Are you using treesitter ?

**Comment by 9seconds** [comment]
Yes. Here is my neovim init.lua: https://github.com/9seconds/dotfiles/blob/master/neovim/init.lua I'm on `0.6.0~ubuntu1+git202112091249-6063e07a0-adeb5640f-bb94ef4f0~ubuntu18.04.1` version now.

**Comment by andersevenrud** [comment]
![Untitled](https://user-images.githubusercontent.com/161548/145579551-56bfb4f1-2557-409c-840e-bd95609b8415.png)

I used the ascinnema side-by-side and wrote it exactly the way you did there, and it did not see any of these issues.

Looks to me like the actual syntax is what's breaking, and not something in this colorscheme :thinking: 

I will try your config when I get back home from work and see if that does not help with reproduction.

**Comment by 9seconds** [comment]
I see. I'm using neovim from nightly so it is very possible that something is broken. I've tried to recompile parsers but no luck. I'll try with a stable later.

**Comment by andersevenrud** [comment]
I'm also on nightly but without issues. **However** I was able to reproduce this with your configuration.

After some digging I found that this happens when change my config to `ensure_installed = 'maintained'` instead of having an explicit list. I'm not quite sure why yet (example: I set it to `{ 'python' }`, but still no issues).

**Comment by 9seconds** [comment]
Thanks! It seems that it is a regression in a parser for RST: https://github.com/stsewd/tree-sitter-rst/issues/22

**Comment by andersevenrud** [comment]
After a process of elimination I found that it's reStructuredText that causes this: https://github.com/stsewd/tree-sitter-rst

Not really sure where to go from here though...

**Comment by andersevenrud** [comment]
Hah. Posted at the same time! I didn't look at the issues yet. Thanks :)
