### ISSUE TITLE
Better support/highlight for hrsh7th/cmp-nvim-lsp-signature-help

### ISSUE THREAD

**Issue by gegoune** [andersevenrud/nordic.nvim#60]
Dropping it here for later as I have no time to look into it right now.

https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/issues/1#issuecomment-1001622027

**Comment by andersevenrud** [comment]
I saw this one while browsing hrsh7th not too long ago. I didn't really take much notice because of the lack of documentation... but is this a cmp way to do https://github.com/ray-x/lsp_signature.nvim ?

**Comment by gegoune** [comment]
Yes, I believe so. It uses cmp's menu to display function's signature.

**Comment by gegoune** [comment]
The way highlighting is done just got changed slightly making it bit more visible. I don't think there is anything thatch be done on nordic side, closing.

https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/commit/3f486a300c7f7296719c0705117afe24e3985766
