### ISSUE TITLE
Add `guisp` support

### ISSUE THREAD

**Issue by meck** [andersevenrud/nordic.nvim#67]
I get the default (non-nord) colors for underlines on  `DiagnosticUnderlineError` `DiagnosticUnderlineHint` `DiagnosticUnderlineWarn` `DiagnosticUnderlineInfo`.

This should be controlled by `guisp` currently they are set with default values:
```
DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red 
```

Looking at the code creating highlight groups It seems nordic dosen't have any support for setting `guisp`

**Comment by andersevenrud** [comment]
Thanks for raising this issue. Support coming now :)
