### ISSUE TITLE
Need to `set termguicolors`

### ISSUE THREAD

**Issue by xulongwu4** [andersevenrud/nordic.nvim#71]
Since `termguicolors` is by default not true in vim/neovim, and this plugin definitely needs `termguicolors` to work correctly, I think we should either mention this explicitly in the README that the user needs to do `set termguicolors` in their vim init files, or `nordic.vim` should `set termguicolors` for the users.

**Comment by andersevenrud** [comment]
Thanks for raising this issue.

> or nordic.vim should set termguicolors for the users.

Just went on a quick github search, and it seems that this is usually set by the theme itself. So I think that is the way to go here as well.

**Comment by andersevenrud** [comment]
I went ahead and added setting `termguicolors` from this theme.

Maybe this should be mentioned in the documentation? If that's the case feel free to re-open this issue.
