### ISSUE TITLE
Add support for double, dashed, and dotted underlines

### ISSUE THREAD

**Issue by gegoune** [andersevenrud/nordic.nvim#74]
Another nvim improvement that can be leveraged by nordic.nvim: https://github.com/neovim/neovim/pull/17589 (for supporting terminal emulators).

Can you think of any feasible applications?

**Comment by andersevenrud** [comment]
These should be added to style table:

https://github.com/andersevenrud/nordic.nvim/blob/35b910263c614257dadc76813c9a02659912ad62/lua/nordic/init.lua#L17
