### ISSUE TITLE
Highlight issues with dressing.nvim

### ISSUE THREAD

**Issue by dsully** [andersevenrud/nordic.nvim#77]
I'm trying to use https://github.com/stevearc/dressing.nvim as a replacement for `vim.ui.input`, however nordic's highlighting is causing some weird issues:

<img width="457" alt="CleanShot 2022-04-10 at 14 06 40@2x" src="https://user-images.githubusercontent.com/22371/162639889-c03dde8e-1bdd-488a-b4bf-8dc2040dcfc5.png">

Where the title should be text that says "Rename To"

At the very least, it looks like non-minimal-mode is missing a `FloatBorder` definition.

**Comment by andersevenrud** [comment]
Nice catch! I also see this now and can't remember it being like this.

~~Probably related to https://github.com/stevearc/dressing.nvim/commit/e14e35a9d46575882f7d2df5b7a051563d1b7b16~~ :thinking:

**Comment by andersevenrud** [comment]
Should be fixed now. Thanks for reporting! :+1:
