### ISSUE TITLE
Escape character (TSStringEscape) is not colored correctly

### ISSUE THREAD

**Issue by dst80** [andersevenrud/nordic.nvim#81]
Hi Anders,
first of all thanks for your plugin. Personally I find it visually more balanced than other nord themes for neovim.

But I found an issue with the escape characters. More precisely, the 'TSStringEscape' is not drawn as expected (yellow). The reason is a typo in line 177 in the syntax.lua file. Instead of 'TSStringEscape' the line says 'TSStriingEscape'.

**Comment by andersevenrud** [comment]
Thanks for letting me know!

Could you maybe make a PR for this ?

**Comment by andersevenrud** [comment]
Fixed in #83
