### ISSUE TITLE
Change of hl for LspReference

### ISSUE THREAD

**Issue by delafthi** [andersevenrud/nordic.nvim#89]
The current hl colors of

- `LspReferenceText`
- `LspReferenceRead`
- `LspReferenceWrite`

are very hard to see. Here a short example:

- Current settings (variables which get a value are sligtly brighter): 
![current](https://user-images.githubusercontent.com/50531499/199804302-a290abe3-0e47-484e-b051-23454fa9e6e2.png)

- With `LspReferenceRead` bg set to purple and `LspReferenceWrite` bg set to orange:
![new example](https://user-images.githubusercontent.com/50531499/199804791-a48a92f5-32de-4e89-b9d5-864a6abf1f1d.png)

I think we do not need to set these hl groups to such dominant colors. However, more visible defaults would be nice. If you want I can make a PR with a suggestion.

These hl groups are used for `vim.buf.lsp.document_highlight` if the lsp supports it. How to activate this feature when resting with the cursor over a variable is described [here](https://github.com/neovim/nvim-lspconfig/wiki/UI-Customization#highlight-symbol-under-cursor).

**Comment by andersevenrud** [comment]
>  If you want I can make a PR with a suggestion.

Please do! :angel:
